/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        navy: {
          50: 'rgb(var(--color-navy-50) / <alpha-value>)',
          100: 'rgb(var(--color-navy-100) / <alpha-value>)',
          200: 'rgb(var(--color-navy-200) / <alpha-value>)',
          300: 'rgb(var(--color-navy-300) / <alpha-value>)',
          400: 'rgb(var(--color-navy-400) / <alpha-value>)',
          500: 'rgb(var(--color-navy-500) / <alpha-value>)',
          600: 'rgb(var(--color-navy-600) / <alpha-value>)',
          700: 'rgb(var(--color-navy-700) / <alpha-value>)',
          800: 'rgb(var(--color-navy-800) / <alpha-value>)',
          900: 'rgb(var(--color-navy-900) / <alpha-value>)',
          950: 'rgb(var(--color-navy-950) / <alpha-value>)',
        },
        gold: {
          50: 'rgb(var(--color-gold-50) / <alpha-value>)',
          100: 'rgb(var(--color-gold-100) / <alpha-value>)',
          200: 'rgb(var(--color-gold-200) / <alpha-value>)',
          300: 'rgb(var(--color-gold-300) / <alpha-value>)',
          400: 'rgb(var(--color-gold-400) / <alpha-value>)',
          500: 'rgb(var(--color-gold-500) / <alpha-value>)',
          600: 'rgb(var(--color-gold-600) / <alpha-value>)',
          700: 'rgb(var(--color-gold-700) / <alpha-value>)',
          800: 'rgb(var(--color-gold-800) / <alpha-value>)',
          900: 'rgb(var(--color-gold-900) / <alpha-value>)',
          950: 'rgb(var(--color-gold-950) / <alpha-value>)',
        },
        crimson: {
          50: 'rgb(var(--color-crimson-50) / <alpha-value>)',
          100: 'rgb(var(--color-crimson-100) / <alpha-value>)',
          200: 'rgb(var(--color-crimson-200) / <alpha-value>)',
          300: 'rgb(var(--color-crimson-300) / <alpha-value>)',
          400: 'rgb(var(--color-crimson-400) / <alpha-value>)',
          500: 'rgb(var(--color-crimson-500) / <alpha-value>)',
          600: 'rgb(var(--color-crimson-600) / <alpha-value>)',
          700: 'rgb(var(--color-crimson-700) / <alpha-value>)',
          800: 'rgb(var(--color-crimson-800) / <alpha-value>)',
          900: 'rgb(var(--color-crimson-900) / <alpha-value>)',
          950: 'rgb(var(--color-crimson-950) / <alpha-value>)',
        },
      },
    },
  },
  plugins: [],
};